=== duplico/badge.lgbt/uniflash_windows_animloader-2021-r1/ccs_base/hercules/flash/schema/PllConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.4" xmlns="">
    <xsd:element name="PllConfig">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" name="Xtal">
                    <xsd:complexType>
                        <xsd:attribute name="Frequency" type="xsd:float"/>
                        <xsd:attribute name="pllCtl1">
                            <xsd:simpleType>
                                <xsd:restriction base="HexType"/>
                            </xsd:simpleType>
                        </xsd:attribute>
                        <xsd:attribute name="pllCtl2">
                            <xsd:simpleType>
                                <xsd:restriction base="HexType"/>
                            </xsd:simpleType>
                        </xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="Type"/>
            <xsd:attribute name="Frequency" type="xsd:integer"/>
            <xsd:attribute name="MinXtal" type="xsd:integer"/>
            <xsd:attribute name="MaxXtal" type="xsd:integer"/>
            <xsd:attribute name="Step" type="xsd:float"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:simpleType name="HexType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="0x[\da-fA-F]{1,8}"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== duplico/badge.lgbt/uniflash_windows_badge-2021-r1/ccs_base/hercules/flash/configs/fmzpll/100.xml
<?xml version="1.0" encoding="UTF-8"?>
<PllConfig
    Type="fmzpll" Frequency="100"  MinXtal="5" MaxXtal="20" Step="0.5" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:../../schema/PllConfig.xsd">
    <Xtal Frequency="5.0"  pllCtl1="0x40017000" pllCtl2="0x00007400"/>
    <Xtal Frequency="5.5"  pllCtl1="0x40016400" pllCtl2="0x00007400"/>
    <Xtal Frequency="6.0"  pllCtl1="0x40016400" pllCtl2="0x00007400"/>
    <Xtal Frequency="6.5"  pllCtl1="0x40028100" pllCtl2="0x00007400"/>
    <Xtal Frequency="7.0"  pllCtl1="0x40027A00" pllCtl2="0x00007400"/>
    <Xtal Frequency="7.5"  pllCtl1="0x40026E00" pllCtl2="0x00007400"/>
    <Xtal Frequency="8.0"  pllCtl1="0x40026800" pllCtl2="0x00007400"/>
    <Xtal Frequency="8.5"  pllCtl1="0x40026300" pllCtl2="0x00007400"/>
    <Xtal Frequency="9.0"  pllCtl1="0x40025E00" pllCtl2="0x00007400"/>
    <Xtal Frequency="9.5"  pllCtl1="0x40037700" pllCtl2="0x00007400"/>
    <Xtal Frequency="10.0" pllCtl1="0x40037100" pllCtl2="0x00007400"/>
    <Xtal Frequency="10.5" pllCtl1="0x40036B00" pllCtl2="0x00007400"/>
    <Xtal Frequency="11.0" pllCtl1="0x40036500" pllCtl2="0x00007400"/>
    <Xtal Frequency="11.5" pllCtl1="0x40036000" pllCtl2="0x00007400"/>
    <Xtal Frequency="12.0" pllCtl1="0x40035B00" pllCtl2="0x00007400"/>
    <Xtal Frequency="12.5" pllCtl1="0x40035B00" pllCtl2="0x00007400"/>
    <Xtal Frequency="13.0" pllCtl1="0x40046C00" pllCtl2="0x00007400"/>
    <Xtal Frequency="13.5" pllCtl1="0x40046600" pllCtl2="0x00007400"/>
    <Xtal Frequency="14.0" pllCtl1="0x40046600" pllCtl2="0x00007400"/>
    <Xtal Frequency="14.5" pllCtl1="0x40046100" pllCtl2="0x00007400"/>
    <Xtal Frequency="15.0" pllCtl1="0x40045C00" pllCtl2="0x00007400"/>
    <Xtal Frequency="15.5" pllCtl1="0x40045C00" pllCtl2="0x00007400"/>
    <Xtal Frequency="16.0" pllCtl1="0x40056900" pllCtl2="0x00007400"/>
    <Xtal Frequency="16.5" pllCtl1="0x40056300" pllCtl2="0x00007400"/>
    <Xtal Frequency="17.0" pllCtl1="0x40056300" pllCtl2="0x00007400"/>
    <Xtal Frequency="17.5" pllCtl1="0x40055E00" pllCtl2="0x00007400"/>
    <Xtal Frequency="18.0" pllCtl1="0x40055E00" pllCtl2="0x00007400"/>
    <Xtal Frequency="18.5" pllCtl1="0x40066800" pllCtl2="0x00007400"/>
    <Xtal Frequency="19.0" pllCtl1="0x40066800" pllCtl2="0x00007400"/>
    <Xtal Frequency="19.5" pllCtl1="0x40066300" pllCtl2="0x00007400"/>
    <Xtal Frequency="20.0" pllCtl1="0x40066300" pllCtl2="0x00007400"/>
</PllConfig>

=== duplico/badge.lgbt/uniflash_windows_badge-2021-r1/ccs_base/hercules/flash/configs/fmzpll/80.xml
<?xml version="1.0" encoding="UTF-8"?>
<PllConfig
    Type="fmzpll" Frequency="80"  MinXtal="5" MaxXtal="20" Step="0.5" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:../../schema/PllConfig.xsd">
    <Xtal Frequency="5.0"  pllCtl1="0x20015F00" pllCtl2="0x00007400"/>
    <Xtal Frequency="5.5"  pllCtl1="0x20017300" pllCtl2="0x00007600"/>
    <Xtal Frequency="6.0"  pllCtl1="0x20016A00" pllCtl2="0x00007600"/>
    <Xtal Frequency="6.5"  pllCtl1="0x20016200" pllCtl2="0x00007600"/>
    <Xtal Frequency="7.0"  pllCtl1="0x20015B00" pllCtl2="0x00007600"/>
    <Xtal Frequency="7.5"  pllCtl1="0x20016A00" pllCtl2="0x00007800"/>
    <Xtal Frequency="8.0"  pllCtl1="0x20016300" pllCtl2="0x00007800"/>
    <Xtal Frequency="8.5"  pllCtl1="0x20015D00" pllCtl2="0x00007800"/>
    <Xtal Frequency="9.0"  pllCtl1="0x20016A00" pllCtl2="0x00007A00"/>
    <Xtal Frequency="9.5"  pllCtl1="0x20016500" pllCtl2="0x00007A00"/>
    <Xtal Frequency="10.0" pllCtl1="0x20015F00" pllCtl2="0x00007A00"/>
    <Xtal Frequency="10.5" pllCtl1="0x20015B00" pllCtl2="0x00007A00"/>
    <Xtal Frequency="11.0" pllCtl1="0x20026D00" pllCtl2="0x00007800"/>
    <Xtal Frequency="11.5" pllCtl1="0x20026800" pllCtl2="0x00007800"/>
    <Xtal Frequency="12.0" pllCtl1="0x20026300" pllCtl2="0x00007800"/>
    <Xtal Frequency="12.5" pllCtl1="0x20025F00" pllCtl2="0x00007800"/>
    <Xtal Frequency="13.0" pllCtl1="0x20025C00" pllCtl2="0x00007800"/>
    <Xtal Frequency="13.5" pllCtl1="0x20026A00" pllCtl2="0x00007A00"/>
    <Xtal Frequency="14.0" pllCtl1="0x20026600" pllCtl2="0x00007A00"/>
    <Xtal Frequency="14.5" pllCtl1="0x20026200" pllCtl2="0x00007A00"/>
    <Xtal Frequency="15.0" pllCtl1="0x20025F00" pllCtl2="0x00007A00"/>
    <Xtal Frequency="15.5" pllCtl1="0x20025C00" pllCtl2="0x00007A00"/>
    <Xtal Frequency="16.0" pllCtl1="0x20036300" pllCtl2="0x00007800"/>
    <Xtal Frequency="16.5" pllCtl1="0x20036000" pllCtl2="0x00007800"/>
    <Xtal Frequency="17.0" pllCtl1="0x20035D00" pllCtl2="0x00007800"/>
    <Xtal Frequency="17.5" pllCtl1="0x20035B00" pllCtl2="0x00007800"/>
    <Xtal Frequency="18.0" pllCtl1="0x20036A00" pllCtl2="0x00007A00"/>
    <Xtal Frequency="18.5" pllCtl1="0x20036700" pllCtl2="0x00007A00"/>
    <Xtal Frequency="19.0" pllCtl1="0x20036500" pllCtl2="0x00007A00"/>
    <Xtal Frequency="19.5" pllCtl1="0x20036200" pllCtl2="0x00007A00"/>
    <Xtal Frequency="20.0" pllCtl1="0x20035F00" pllCtl2="0x00007A00"/>
</PllConfig>

=== duplico/badge.lgbt/uniflash_windows_badge-2021-r1/ccs_base/hercules/flash/configs/fmzpll/40.xml
<?xml version="1.0" encoding="UTF-8"?>
<PllConfig
    Type="fmzpll" Frequency="40"  MinXtal="5" MaxXtal="20" Step="0.5" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:../../schema/PllConfig.xsd">
    <Xtal Frequency="5.0"  pllCtl1="0x40017500" pllCtl2="0x00007E00"/>
    <Xtal Frequency="5.5"  pllCtl1="0x40016900" pllCtl2="0x00007E00"/>
    <Xtal Frequency="6.0"  pllCtl1="0x40016300" pllCtl2="0x00007E00"/>
    <Xtal Frequency="6.5"  pllCtl1="0x40028600" pllCtl2="0x00007E00"/>
    <Xtal Frequency="7.0"  pllCtl1="0x40027F00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="7.5"  pllCtl1="0x40027800" pllCtl2="0x00007E00"/>
    <Xtal Frequency="8.0"  pllCtl1="0x40026C00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="8.5"  pllCtl1="0x40026600" pllCtl2="0x00007E00"/>
    <Xtal Frequency="9.0"  pllCtl1="0x40026100" pllCtl2="0x00007E00"/>
    <Xtal Frequency="9.5"  pllCtl1="0x40025C00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="10.0" pllCtl1="0x40037500" pllCtl2="0x00007E00"/>
    <Xtal Frequency="10.5" pllCtl1="0x40036F00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="11.0" pllCtl1="0x40036900" pllCtl2="0x00007E00"/>
    <Xtal Frequency="11.5" pllCtl1="0x40036900" pllCtl2="0x00007E00"/>
    <Xtal Frequency="12.0" pllCtl1="0x40036300" pllCtl2="0x00007E00"/>
    <Xtal Frequency="12.5" pllCtl1="0x40035E00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="13.0" pllCtl1="0x40047000" pllCtl2="0x00007E00"/>
    <Xtal Frequency="13.5" pllCtl1="0x40046A00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="14.0" pllCtl1="0x40046A00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="14.5" pllCtl1="0x40046400" pllCtl2="0x00007E00"/>
    <Xtal Frequency="15.0" pllCtl1="0x40046400" pllCtl2="0x00007E00"/>
    <Xtal Frequency="15.5" pllCtl1="0x40045F00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="16.0" pllCtl1="0x40056C00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="16.5" pllCtl1="0x40056C00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="17.0" pllCtl1="0x40056600" pllCtl2="0x00007E00"/>
    <Xtal Frequency="17.5" pllCtl1="0x40056600" pllCtl2="0x00007E00"/>
    <Xtal Frequency="18.0" pllCtl1="0x40056100" pllCtl2="0x00007E00"/>
    <Xtal Frequency="18.5" pllCtl1="0x40056100" pllCtl2="0x00007E00"/>
    <Xtal Frequency="19.0" pllCtl1="0x40055C00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="19.5" pllCtl1="0x40055C00" pllCtl2="0x00007E00"/>
    <Xtal Frequency="20.0" pllCtl1="0x40066600" pllCtl2="0x00007E00"/>
</PllConfig>
